name: flutter_folds

environment:
  sdk: ">=2.18.0 <3.0.0"

publish_to: none

dependencies:
  any_syntax_highlighter: ^0.0.13
  dart_style: ^2.3.0
  flutter:
    sdk: flutter
  flutter_fancy_tree_view: ^1.1.0
  flutter_solidart: ^0.3.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  localstore: ^1.3.5
  modals: ^1.0.0+1
  searchable_listview: ^2.2.2
  widget_models:

dev_dependencies:
  build_runner: ^2.3.3
  extra_pedantic: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  melos: ^3.0.0
  solidart_lint: ^0.1.3

flutter:
  uses-material-design: true
